VirtualSecretary/Controllers/CereriSchimbareOptionaleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Data.Core.Domain;
using Data.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using VirtualSecretary.Authorization;
using VirtualSecretary.Models;
using VirtualSecretary.Services;

namespace VirtualSecretary.Controllers
{
    public class CereriSchimbareOptionaleController : Controller
    {
        private readonly CereriDatabaseService _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public CereriSchimbareOptionaleController(CereriDatabaseService context, IAuthorizationService authorizationService,
            UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _authorizationService = authorizationService;
            _emailSender = emailSender;
        }

        // GET: CereriSchimbareOptionale
        public async Task<IActionResult> Index()
        {
            var cereriSchimbareOptionale = from c in _context.CereriSchimbareOptionale select c;
            var isAuthorized = User.IsInRole("Admin") || User.IsInRole("Secretar");
            var currentUserId = _userManager.GetUserId(User);
            if (!isAuthorized)
            {
                cereriSchimbareOptionale = cereriSchimbareOptionale.Where(c => c.OwnerID == currentUserId);
            }
            return View(await cereriSchimbareOptionale.ToListAsync());
        }

        // GET: CereriSchimbareOptionale/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cerereSchimbareOptionale = await _context.CereriSchimbareOptionale
                .SingleOrDefaultAsync(m => m.Id == id);
            if (cerereSchimbareOptionale == null)
            {
                return NotFound();
            }

            return View(cerereSchimbareOptionale);
        }

        // GET: CereriSchimbareOptionale/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CereriSchimbareOptionale/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OptionalVechi,OptionalNou,Id,OwnerID,Nume,Prenume,InitialaTatalui,Email,NumarMatricol,SerieBuletin,NumarBuletin,Stare")] CerereSchimbareOptionale cerereSchimbareOptionale)
        {
            if (ModelState.IsValid)
            {
                cerereSchimbareOptionale.Id = Guid.NewGuid();
                cerereSchimbareOptionale.OwnerID = _userManager.GetUserId(User);
                var isAuthorized = await _authorizationService.AuthorizeAsync(User,
                    cerereSchimbareOptionale, CereriOperatii.Create);
                if (!isAuthorized.Succeeded)
                {
                    return new ChallengeResult();
                }
                _context.Add(cerereSchimbareOptionale);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cerereSchimbareOptionale);
        }

        // GET: CereriSchimbareOptionale/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cerereSchimbareOptionale = await _context.CereriSchimbareOptionale.SingleOrDefaultAsync(m => m.Id == id);
            if (cerereSchimbareOptionale == null)
            {
                return NotFound();
            }
            return View(cerereSchimbareOptionale);
        }

        // POST: CereriSchimbareOptionale/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("OptionalVechi,OptionalNou,Id,OwnerID,Nume,Prenume,InitialaTatalui,Email,NumarMatricol,SerieBuletin,NumarBuletin,Stare")] CerereSchimbareOptionale cerereSchimbareOptionale)
        {
            cerereSchimbareOptionale.OwnerID = _userManager.GetUserId(User);
            if (id != cerereSchimbareOptionale.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cerereSchimbareOptionale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CerereSchimbareOptionaleExists(cerereSchimbareOptionale.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cerereSchimbareOptionale);
        }

        // GET: CereriSchimbareOptionale/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cerereSchimbareOptionale = await _context.CereriSchimbareOptionale
                .SingleOrDefaultAsync(m => m.Id == id);
            if (cerereSchimbareOptionale == null)
            {
                return NotFound();
            }

            return View(cerereSchimbareOptionale);
        }

        // POST: CereriSchimbareOptionale/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var cerereSchimbareOptionale = await _context.CereriSchimbareOptionale.SingleOrDefaultAsync(m => m.Id == id);
            _context.CereriSchimbareOptionale.Remove(cerereSchimbareOptionale);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CerereSchimbareOptionaleExists(Guid id)
        {
            return _context.CereriSchimbareOptionale.Any(e => e.Id == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetStatus(Guid id, Cerere.StareCerere status,String motiv)
        {
            var cerereSchimbareOptionale = await _context.CereriSchimbareOptionale.SingleOrDefaultAsync(m => m.Id == id);
            var isAuthorized = User.IsInRole("Admin") || User.IsInRole("Secretar");

            if (!isAuthorized)
            {
                return new ChallengeResult();
            }
            cerereSchimbareOptionale.Stare = status;
            _context.CereriSchimbareOptionale.Update(cerereSchimbareOptionale);
            await _context.SaveChangesAsync();

            if (status == Cerere.StareCerere.Aprobata)
            {
                await _emailSender.SendEmailAsync(cerereSchimbareOptionale.Email, "Cerere " + status,
                    "Cererea cu id-ul: "
                    + cerereSchimbareOptionale.Id + " a fost " + status + ". \n\nDetaliile cererii:" +
                    "\n\tOptional nou: " + cerereSchimbareOptionale.OptionalNou +
                    "\n\tOptional vechi: " + cerereSchimbareOptionale.OptionalVechi +
                    "\n\tNume: " + cerereSchimbareOptionale.Nume +
                    "\n\tPrenume: " + cerereSchimbareOptionale.Prenume +
                    "\n\tInitiala tatalui: " + cerereSchimbareOptionale.InitialaTatalui +
                    "\n\tNumar buletin: " + cerereSchimbareOptionale.NumarBuletin +
                    "\n\tNumar matricol: " + cerereSchimbareOptionale.NumarMatricol +
                    "\n\tSerie buletin: " + cerereSchimbareOptionale.SerieBuletin);
            }
            else
            {
                await _emailSender.SendEmailAsync(cerereSchimbareOptionale.Email, "Cerere " + status,
                    "Cererea cu id-ul: "
                    + cerereSchimbareOptionale.Id + " a fost " + status + ".\nMotivul respingerii: "+motiv+" \n\nDetaliile cererii:" +
                    "\n\tOptional nou: " + cerereSchimbareOptionale.OptionalNou +
                    "\n\tOptional vechi: " + cerereSchimbareOptionale.OptionalVechi +
                    "\n\tNume: " + cerereSchimbareOptionale.Nume +
                    "\n\tPrenume: " + cerereSchimbareOptionale.Prenume +
                    "\n\tInitiala tatalui: " + cerereSchimbareOptionale.InitialaTatalui +
                    "\n\tNumar buletin: " + cerereSchimbareOptionale.NumarBuletin +
                    "\n\tNumar matricol: " + cerereSchimbareOptionale.NumarMatricol +
                    "\n\tSerie buletin: " + cerereSchimbareOptionale.SerieBuletin);
            }
            return RedirectToAction("Index");
        }
    }
}

VirtualSecretary/Views/CereriSchimbareOptionale/Create.cshtml
@model Data.Core.Domain.CerereSchimbareOptionale

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCerereSchimbareOptionale">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OptionalVechi" class="control-label"></label>
                <input asp-for="OptionalVechi" class="form-control" />
                <span asp-validation-for="OptionalVechi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionalNou" class="control-label"></label>
                <input asp-for="OptionalNou" class="form-control" />
                <span asp-validation-for="OptionalNou" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nume" class="control-label"></label>
                <input asp-for="Nume" class="form-control" />
                <span asp-validation-for="Nume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenume" class="control-label"></label>
                <input asp-for="Prenume" class="form-control" />
                <span asp-validation-for="Prenume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InitialaTatalui" class="control-label"></label>
                <input asp-for="InitialaTatalui" class="form-control" />
                <span asp-validation-for="InitialaTatalui" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumarMatricol" class="control-label"></label>
                <input asp-for="NumarMatricol" class="form-control" />
                <span asp-validation-for="NumarMatricol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerieBuletin" class="control-label"></label>
                <input asp-for="SerieBuletin" class="form-control" />
                <span asp-validation-for="SerieBuletin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumarBuletin" class="control-label"></label>
                <input asp-for="NumarBuletin" class="form-control" />
                <span asp-validation-for="NumarBuletin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Înapoi</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VirtualSecretary/Views/CereriSchimbareOptionale/Delete.cshtml
@model Data.Core.Domain.CerereSchimbareOptionale

@{
    ViewData["Title"] = "Șterge";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" type="text/css" href="~/css/tip-cereri-index.css">
</head>
<div class="content">
    <div class="tip_cerere" onclick="location.href = '/CereriSchimbareOptionale'">
        <span>Înapoi</span>
    </div>
</div>
<div class="actiune">
    <h3>Sunteți sigur că doriți să ștergeți cererea?</h3>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            Opțional vechi:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptionalVechi)
        </dd>
        <dt>
            Opțional nou:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptionalNou)
        </dd>
        <dt>
            Nume:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nume)
        </dd>
        <dt>
            Prenume:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prenume)
        </dd>
        <dt>
            Inițiala tatălui:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InitialaTatalui)
        </dd>
        <dt>
            Email:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            Număr matricol:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumarMatricol)
        </dd>
        <dt>
            Serie buletin:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SerieBuletin)
        </dd>
        <dt>
            Număr buletin:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumarBuletin)
        </dd>
        <dt>
            Stare:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stare)
        </dd>
    </dl>
    <hr/>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input class="tip_cerere" type="submit" value="Șterge"/>
    </form>
</div>

VirtualSecretary/Views/CereriSchimbareOptionale/Details.cshtml
@using Data.Core.Domain
@model CerereSchimbareOptionale
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@inject IAuthorizationService AuthorizationService
@{
    ViewData["Title"] = "Detalii";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" type="text/css" href="~/css/tip-cereri-index.css">
    <script src="~/js/pop-up.js"></script>
</head>
<div class="content">
    <div class="tip_cerere" onclick="location.href = '/CereriSchimbareOptionale'">
        <span>Înapoi</span>
    </div>
</div>
<div class="actiune">
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Opțional vechi: 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptionalVechi)
        </dd>
        <dt>
            Opțional nou: 
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptionalNou)
        </dd>
        <dt>
            Nume:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nume)
        </dd>
        <dt>
            Prenume:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prenume)
        </dd>
        <dt>
            Inițiala tatălui:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InitialaTatalui)
        </dd>
        <dt>
            Email:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            Număr matricol:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumarMatricol)
        </dd>
        <dt>
            Serie buletin:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SerieBuletin)
        </dd>
        <dt>
            Număr buletin:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumarBuletin)
        </dd>
        <dt>
            Stare:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stare)
        </dd>
    </dl>
</div>
@if (User.IsInRole("Admin") || User.IsInRole("Secretar") && Model.Stare == Cerere.StareCerere.Trimisa)
{
    <form asp-action="SetStatus" asp-controller="CereriSchimbareOptionale" style="display:inline;">
        <input type="hidden" name="id" value="@Model.Id" />
        <input type="hidden" name="status" value="@Cerere.StareCerere.Aprobata" />
        <button style="width: 100px; height: 50px; font-size: 17px;margin-bottom: 15px;" type="submit" class="btn btn-xs btn-success">Acceptă</button>
    </form>
    <button id="myBtn" style="width: 100px; height: 50px; font-size: 17px;margin-bottom: 15px; margin-left: 10px;" class="btn btn-xs btn-danger">Respinge</button>
    <div id="myModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p style="text-align: center; font-size: 20px; color: white">Vă rugăm să completați motivul respingerii:</p>
            <form asp-action="SetStatus" asp-controller="CereriSchimbareOptionale" style="display:inline;">
                <input type="hidden" name="id" value="@Model.Id" />
                <input type="hidden" name="status" value="@Cerere.StareCerere.Respinsa" />
                <input class="motiv" type="text" name="motiv" autofocus required/>
                <button id="respinge" style="width: 100px; height: 50px; font-size: 17px; margin-top: 10px;" class="btn btn-xs btn-danger">Respinge</button>
            </form>
        </div>
    </div>
}
<div>
    @if (User.IsInRole("Admin") || !User.IsInRole("Secretar") && Model.Stare == Cerere.StareCerere.Trimisa)
    {
        <div class="content">
            <a class="tip_cerere" asp-action="Edit" asp-route-id="@Model.Id">
                <span>Editează</span>
            </a>
        </div>
    }
</div>

VirtualSecretary/Views/CereriSchimbareOptionale/Edit.cshtml
@model Data.Core.Domain.CerereSchimbareOptionale

@{
    ViewData["Title"] = "Editează";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" type="text/css" href="~/css/tip-cereri-index.css">
</head>
<div class="content">
    <div class="tip_cerere" onclick="location.href = '/CereriSchimbareOptionale'">
        <span>Înapoi</span>
    </div>
</div> 
<div class="actiune"> 
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="OptionalVechi" class="control-label">Opțional vechi</label>
                    <input asp-for="OptionalVechi" class="form-control" placeholder="CSSO" />
                    <span asp-validation-for="OptionalVechi" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OptionalNou" class="control-label">Opțional nou</label>
                    <input asp-for="OptionalNou" class="form-control" placeholder="DAWNC" />
                    <span asp-validation-for="OptionalNou" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nume" class="control-label">Nume</label>
                    <input asp-for="Nume" class="form-control" placeholder="Popescu" />
                    <span asp-validation-for="Nume" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Prenume" class="control-label">Prenume</label>
                    <input asp-for="Prenume" class="form-control" placeholder="Ion" />
                    <span asp-validation-for="Prenume" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="InitialaTatalui" class="control-label">Inițiala tatălui</label>
                    <input asp-for="InitialaTatalui" class="form-control" placeholder="M." />
                    <span asp-validation-for="InitialaTatalui" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">Email</label>
                    <input asp-for="Email" class="form-control" placeholder="ionpopescu@gmail.com" type="email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NumarMatricol" class="control-label">Număr matricol</label>
                    <input asp-for="NumarMatricol" class="form-control" placeholder="12345678SL123456" />
                    <span asp-validation-for="NumarMatricol" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SerieBuletin" class="control-label">Serie buletin</label>
                    <input asp-for="SerieBuletin" class="form-control" placeholder="MZ" />
                    <span asp-validation-for="SerieBuletin" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NumarBuletin" class="control-label">Număr buletin</label>
                    <input asp-for="NumarBuletin" class="form-control" placeholder="123456" />
                    <span asp-validation-for="NumarBuletin" class="text-danger"></span>
                </div>
                <div class="form-group content">
                    <input class="tip_cerere" type="submit" value="Salvează"/>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VirtualSecretary/Views/CereriSchimbareOptionale/Index.cshtml
@using Data.Core.Domain
@model IEnumerable<CerereSchimbareOptionale>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" type="text/css" href="~/css/table.css">
    <link rel="stylesheet" type="text/css" href="~/css/tip-cereri-index.css">
</head>
<body>
<div class="content">
    @if (!User.IsInRole("Admin") && !User.IsInRole("Secretar"))
    {
        <div id="tipCerere" data-tip="SchimbareOptionale" class="tip_cerere cerere" onclick="location.href = '/Cereri/Create'">
            <span>Depune o cerere nouă</span>
        </div>
    }
    <div class="tip_cerere" onclick="location.href = '/Cereri'">
        <span>Înapoi</span>
    </div>
</div>
    <table>
        <thead class="tbl-header">
            <tr>
                <th> Opțional vechi </th>
                <th> Opțional nou </th>
                <th> Nume </th>
                <th> Prenume </th>
                <th> Inițiala tatălui </th>
                <th> Email </th>
                <th> Număr matricol </th>
                <th> Serie buletin </th>
                <th> Număr buletin </th>
                <th> Stare </th>
                <th></th>
            </tr>
        </thead>
        <tbody class="tbl-content">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OptionalVechi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OptionalNou)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nume)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prenume)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.InitialaTatalui)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumarMatricol)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SerieBuletin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumarBuletin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Stare)
                    </td>
                    <td>
                        @if (User.IsInRole("Admin") || !User.IsInRole("Secretar") && item.Stare == Cerere.StareCerere.Trimisa)
                        {
                            <a style="color: white" asp-action="Edit" asp-route-id="@item.Id">Editează</a>
                        }
                        <a style="color: white" asp-action="Details" asp-route-id="@item.Id">Detalii</a>
                        @if (User.IsInRole("Admin") || !User.IsInRole("Secretar") && item.Stare == Cerere.StareCerere.Trimisa)
                        {
                            <a style="color: white" asp-action="Delete" asp-route-id="@item.Id">Șterge</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>
    
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="@Url.Content("~/js/index.js")"></script>
}